# Generated by Django 4.1.4 on 2022-12-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marvel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('ability', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Man', 'Man'), ('Women', 'Women')], max_length=6)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='media/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
