# Generated by Django 4.1.4 on 2022-12-27 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marvel',
            old_name='image',
            new_name='photo',
        ),
    ]
